[package]
name = "ercp_basic_example"
version = "0.1.0"
authors = ["Jean-Philippe Cugnet <jean-philippe@cugnet.eu>"]
edition = "2018"

[dependencies]
cortex-m-rtic = "0.5.6"
panic-rtt-target = { version = "0.1.2", features = ["cortex-m"] }
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
stm32l4xx-hal = { version = "0.6.0", features = ["stm32l4x6", "rt" ] }

# For `cargo fix` to work.
[[bin]]
name = "ercp_basic_example"
test = false
bench = false
