[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip LPC55S69JBD100"
rustflags = [
    "-C", "linker=flip-link",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv8m.main-none-eabihf" # Cortex-M33
